name: CI build
on: [push]
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - run: npm ci
      - run: npm run check-format
      - run: npm run lint
      - run: npm test
      - run: npm run test:coverage
      - run: npm run test:e2e
      - run: npm run build
